### ISSUE TITLE
is there a way to achieve categories/sub-categories?

### ISSUE THREAD

**Issue by rnvijay** [phanbook/phanbook#219] opened 2017-01-11 08:07 UTC
I like things organized in drill down fashion -- is there a way i can achieve this?

thanks

**Comment by duythien** [comment] 2017-01-12 01:10
At the moment we have not sub categories

**Comment by Ultimater** [comment] 2017-08-18 02:43
Not currently. Duplicate of https://github.com/phanbook/phanbook/issues/34  
I'm working on adding a way.

**Closed as completed** 2017-08-18 18:41 UTC
Labels: duplicate, question
